"""Initial migration latest codes

Revision ID: 74d1a21ca61b
Revises: efd900b9119d
Create Date: 2025-05-30 10:47:42.871491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d1a21ca61b'
down_revision = 'efd900b9119d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
