"""Initial migration latest

Revision ID: 9cfabb5ce34a
Revises: d14c558219f8
Create Date: 2025-05-28 17:30:29.136043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cfabb5ce34a'
down_revision = 'd14c558219f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'AddressLine1',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('addresses', 'City',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('addresses', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('addresses', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('carts', 'TotalItemsCount',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('carts', 'TotalTax',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('carts', 'TotalDiscount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('carts', 'TotalAmount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('carts', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('coupons', 'Name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('coupons', 'Description',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('coupons', 'CouponCode',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('coupons', 'Discount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('coupons', 'DiscountType',
               existing_type=mysql.ENUM('FLAT', 'PERCENTAGE'),
               nullable=False)
    op.alter_column('coupons', 'DiscountPercentage',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('coupons', 'DiscountMaxAmount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('coupons', 'MaxUsage',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('coupons', 'MaxUsagePerUser',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('coupons', 'MaxUsagePerOrder',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('coupons', 'MinOrderAmount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('coupons', 'IsActive',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('coupons', 'IsDeleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('coupons', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('customer_addresses', 'AddressType',
               existing_type=mysql.ENUM('WORK', 'HOME', 'SHIPPING', 'BILLING', 'UNSPECIFIED'),
               nullable=False)
    op.alter_column('customer_addresses', 'IsFavorite',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('customers', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('merchants', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('merchants', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('order_coupons', 'DiscountValue',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('order_coupons', 'DiscountPercentage',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('order_coupons', 'DiscountMaxAmount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('order_coupons', 'Applied',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('order_coupons', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('order_coupons', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('order_histories', 'Timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('order_line_items', 'Quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('order_line_items', 'UnitPrice',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('order_line_items', 'Discount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('order_line_items', 'Tax',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('order_line_items', 'ItemSubTotal',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('order_types', 'Name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('order_types', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('order_types', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('orders', 'OrderStatus',
               existing_type=mysql.ENUM('DRAFT', 'INVENTRY_CHECKED', 'PLACED', 'CONFIRMED', 'PAYMENT_INITIATED', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'CANCELLED', 'SHIPPED', 'DELIVERED', 'CLOSED', 'REOPENED', 'RETURN_INITIATED', 'RETURNED', 'REFUND_INITIATED', 'REFUNDED', 'EXCHANGE_INITIATED', 'EXCHANGED'),
               nullable=False)
    op.alter_column('orders', 'TotalItemsCount',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'OrderDiscount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('orders', 'TipApplicable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('orders', 'TipAmount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('orders', 'TotalTax',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('orders', 'TotalDiscount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('orders', 'TotalAmount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('orders', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('orders', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('payment_transactions', 'PaymentStatus',
               existing_type=mysql.ENUM('INITIATED', 'INPROGRESS', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED', 'EXPIRED', 'UNKNOWN'),
               nullable=False)
    op.alter_column('payment_transactions', 'PaymentAmount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('payment_transactions', 'InitiatedDate',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('payment_transactions', 'CompletedDate',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('payment_transactions', 'IsRefund',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('payment_transactions', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payment_transactions', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_transactions', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('payment_transactions', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payment_transactions', 'IsRefund',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('payment_transactions', 'CompletedDate',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('payment_transactions', 'InitiatedDate',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('payment_transactions', 'PaymentAmount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('payment_transactions', 'PaymentStatus',
               existing_type=mysql.ENUM('INITIATED', 'INPROGRESS', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED', 'EXPIRED', 'UNKNOWN'),
               nullable=True)
    op.alter_column('orders', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('orders', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('orders', 'TotalAmount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('orders', 'TotalDiscount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('orders', 'TotalTax',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('orders', 'TipAmount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('orders', 'TipApplicable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('orders', 'OrderDiscount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('orders', 'TotalItemsCount',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'OrderStatus',
               existing_type=mysql.ENUM('DRAFT', 'INVENTRY_CHECKED', 'PLACED', 'CONFIRMED', 'PAYMENT_INITIATED', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'CANCELLED', 'SHIPPED', 'DELIVERED', 'CLOSED', 'REOPENED', 'RETURN_INITIATED', 'RETURNED', 'REFUND_INITIATED', 'REFUNDED', 'EXCHANGE_INITIATED', 'EXCHANGED'),
               nullable=True)
    op.alter_column('order_types', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('order_types', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('order_types', 'Name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('order_line_items', 'ItemSubTotal',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('order_line_items', 'Tax',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('order_line_items', 'Discount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('order_line_items', 'UnitPrice',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('order_line_items', 'Quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('order_histories', 'Timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('order_coupons', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('order_coupons', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('order_coupons', 'Applied',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('order_coupons', 'DiscountMaxAmount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('order_coupons', 'DiscountPercentage',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('order_coupons', 'DiscountValue',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('merchants', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('merchants', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('customers', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('customer_addresses', 'IsFavorite',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('customer_addresses', 'AddressType',
               existing_type=mysql.ENUM('WORK', 'HOME', 'SHIPPING', 'BILLING', 'UNSPECIFIED'),
               nullable=True)
    op.alter_column('coupons', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('coupons', 'IsDeleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('coupons', 'IsActive',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('coupons', 'MinOrderAmount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('coupons', 'MaxUsagePerOrder',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('coupons', 'MaxUsagePerUser',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('coupons', 'MaxUsage',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('coupons', 'DiscountMaxAmount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('coupons', 'DiscountPercentage',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('coupons', 'DiscountType',
               existing_type=mysql.ENUM('FLAT', 'PERCENTAGE'),
               nullable=True)
    op.alter_column('coupons', 'Discount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('coupons', 'CouponCode',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('coupons', 'Description',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('coupons', 'Name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('carts', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('carts', 'TotalAmount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('carts', 'TotalDiscount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('carts', 'TotalTax',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('carts', 'TotalItemsCount',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('addresses', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('addresses', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('addresses', 'City',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('addresses', 'AddressLine1',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
