"""Initial migration

Revision ID: d14c558219f8
Revises: 
Create Date: 2025-05-28 13:12:49.509752

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd14c558219f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('AddressLine1', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('AddressLine2', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('City', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('State', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('Country', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('ZipCode', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('CreatedBy', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('CustomerId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('TotalItemsCount', sa.Integer(), nullable=False),
    sa.Column('TotalTax', sa.Float(), nullable=False),
    sa.Column('TotalDiscount', sa.Float(), nullable=False),
    sa.Column('TotalAmount', sa.Float(), nullable=False),
    sa.Column('CartToOrderTimestamp', sa.DateTime(), nullable=True),
    sa.Column('AssociatedOrderId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('Description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('CouponCode', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('CouponType', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('Discount', sa.Float(), nullable=False),
    sa.Column('DiscountType', sa.Enum('FLAT', 'PERCENTAGE', name='discounttypes'), nullable=False),
    sa.Column('DiscountPercentage', sa.Float(), nullable=False),
    sa.Column('DiscountMaxAmount', sa.Float(), nullable=False),
    sa.Column('StartDate', sa.DateTime(), nullable=True),
    sa.Column('EndDate', sa.DateTime(), nullable=True),
    sa.Column('MaxUsage', sa.Integer(), nullable=False),
    sa.Column('MaxUsagePerUser', sa.Integer(), nullable=False),
    sa.Column('MaxUsagePerOrder', sa.Integer(), nullable=False),
    sa.Column('MinOrderAmount', sa.Float(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('CreatedBy', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('CouponCode')
    )
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.create_table('order_types',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('Description', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_types_id'), 'order_types', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('ReferenceId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('Email', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('PhoneCode', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('Phone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('ProfilePicture', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('TaxNumber', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('DefaultShippingAddressId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('DefaultBillingAddressId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['DefaultBillingAddressId'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['DefaultShippingAddressId'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Phone'),
    sa.UniqueConstraint('ReferenceId'),
    sa.UniqueConstraint('TaxNumber')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('ReferenceId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('Email', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('Phone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('Logo', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('WebsiteUrl', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('TaxNumber', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('GSTNumber', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('AddressId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AddressId'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('GSTNumber'),
    sa.UniqueConstraint('Phone'),
    sa.UniqueConstraint('ReferenceId'),
    sa.UniqueConstraint('TaxNumber')
    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_table('customer_addresses',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('CustomerId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('AddressId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('AddressType', sa.Enum('WORK', 'HOME', 'SHIPPING', 'BILLING', 'UNSPECIFIED', name='addresstypes'), nullable=False),
    sa.Column('IsFavorite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['AddressId'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['CustomerId'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_addresses_id'), 'customer_addresses', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('DisplayCode', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('OrderStatus', sa.Enum('DRAFT', 'INVENTRY_CHECKED', 'PLACED', 'CONFIRMED', 'PAYMENT_INITIATED', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'CANCELLED', 'SHIPPED', 'DELIVERED', 'CLOSED', 'REOPENED', 'RETURN_INITIATED', 'RETURNED', 'REFUND_INITIATED', 'REFUNDED', 'EXCHANGE_INITIATED', 'EXCHANGED', name='orderstatustypes'), nullable=False),
    sa.Column('InvoiceNumber', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('AssociatedCartId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('TotalItemsCount', sa.Integer(), nullable=False),
    sa.Column('OrderDiscount', sa.Float(), nullable=False),
    sa.Column('TipApplicable', sa.Boolean(), nullable=False),
    sa.Column('TipAmount', sa.Float(), nullable=False),
    sa.Column('TotalTax', sa.Float(), nullable=False),
    sa.Column('TotalDiscount', sa.Float(), nullable=False),
    sa.Column('TotalAmount', sa.Float(), nullable=False),
    sa.Column('Notes', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('CustomerId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('ShippingAddressId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('BillingAddressId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('OrderType', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AssociatedCartId'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['BillingAddressId'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['CustomerId'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['OrderType'], ['order_types.id'], ),
    sa.ForeignKeyConstraint(['ShippingAddressId'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_DisplayCode'), 'orders', ['DisplayCode'], unique=True)
    op.create_index(op.f('ix_orders_InvoiceNumber'), 'orders', ['InvoiceNumber'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('order_coupons',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('Code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('CouponId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('OrderId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('DiscountValue', sa.Float(), nullable=False),
    sa.Column('DiscountPercentage', sa.Float(), nullable=False),
    sa.Column('DiscountMaxAmount', sa.Float(), nullable=False),
    sa.Column('Applied', sa.Boolean(), nullable=False),
    sa.Column('AppliedAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CouponId'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['OrderId'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_coupons_id'), 'order_coupons', ['id'], unique=False)
    op.create_table('order_histories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('OrderId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('PreviousStatus', sa.Enum('DRAFT', 'INVENTRY_CHECKED', 'PLACED', 'CONFIRMED', 'PAYMENT_INITIATED', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'CANCELLED', 'SHIPPED', 'DELIVERED', 'CLOSED', 'REOPENED', 'RETURN_INITIATED', 'RETURNED', 'REFUND_INITIATED', 'REFUNDED', 'EXCHANGE_INITIATED', 'EXCHANGED', name='orderstatustypes'), nullable=True),
    sa.Column('Status', sa.Enum('DRAFT', 'INVENTRY_CHECKED', 'PLACED', 'CONFIRMED', 'PAYMENT_INITIATED', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'CANCELLED', 'SHIPPED', 'DELIVERED', 'CLOSED', 'REOPENED', 'RETURN_INITIATED', 'RETURNED', 'REFUND_INITIATED', 'REFUNDED', 'EXCHANGE_INITIATED', 'EXCHANGED', name='orderstatustypes'), nullable=True),
    sa.Column('UpdatedByUserId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['OrderId'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_histories_id'), 'order_histories', ['id'], unique=False)
    op.create_table('order_line_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('CatalogId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Float(), nullable=False),
    sa.Column('Discount', sa.Float(), nullable=False),
    sa.Column('DiscountSchemeId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('Tax', sa.Float(), nullable=False),
    sa.Column('ItemSubTotal', sa.Float(), nullable=False),
    sa.Column('OrderId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('CartId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['CartId'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['OrderId'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_line_items_id'), 'order_line_items', ['id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('DisplayCode', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('InvoiceNumber', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('BankTransactionId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('PaymentGatewayTransactionId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('PaymentStatus', sa.Enum('INITIATED', 'INPROGRESS', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED', 'EXPIRED', 'UNKNOWN', name='paymentstatustypes'), nullable=False),
    sa.Column('PaymentMode', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('PaymentAmount', sa.Float(), nullable=False),
    sa.Column('PaymentCurrency', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('InitiatedDate', sa.DateTime(), nullable=False),
    sa.Column('CompletedDate', sa.DateTime(), nullable=False),
    sa.Column('PaymentResponse', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('PaymentResponseCode', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('InitiatedBy', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('CustomerId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('OrderId', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('IsRefund', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerId'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['OrderId'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_DisplayCode'), 'payment_transactions', ['DisplayCode'], unique=True)
    op.create_index(op.f('ix_payment_transactions_InvoiceNumber'), 'payment_transactions', ['InvoiceNumber'], unique=True)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_InvoiceNumber'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_DisplayCode'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_order_line_items_id'), table_name='order_line_items')
    op.drop_table('order_line_items')
    op.drop_index(op.f('ix_order_histories_id'), table_name='order_histories')
    op.drop_table('order_histories')
    op.drop_index(op.f('ix_order_coupons_id'), table_name='order_coupons')
    op.drop_table('order_coupons')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_InvoiceNumber'), table_name='orders')
    op.drop_index(op.f('ix_orders_DisplayCode'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customer_addresses_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_order_types_id'), table_name='order_types')
    op.drop_table('order_types')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
