"""Initial migration latest code

Revision ID: efd900b9119d
Revises: 9cfabb5ce34a
Create Date: 2025-05-29 10:46:53.885784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd900b9119d'
down_revision = '9cfabb5ce34a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
