"""empty message

Revision ID: 93978ecba2db
Revises: d29b3e8c3bd0
Create Date: 2023-07-05 18:43:53.765840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93978ecba2db'
down_revision = 'd29b3e8c3bd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
