"""empty message

Revision ID: 414e4d7d1578
Revises: ebcc74ca53ee
Create Date: 2023-07-10 17:40:24.024894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414e4d7d1578'
down_revision = 'ebcc74ca53ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
