"""empty message

Revision ID: d29b3e8c3bd0
Revises: 
Create Date: 2023-07-05 16:53:33.340280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd29b3e8c3bd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_addresses', 'CreatedAt')
    op.drop_column('customer_addresses', 'UpdatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_addresses', sa.Column('UpdatedAt', mysql.DATETIME(), nullable=True))
    op.add_column('customer_addresses', sa.Column('CreatedAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###
